//
//  ShareWorker.swift
//  PocketReader
//
//  Created by Jakub Lares on 20.08.18.
//  Copyright (c) 2018 Jakub Lares. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShareWorker {
    
    func shareArticle(_ article: Article?) {
        guard let article = article else { return }
        let textToShare = [article.title, article.url].compactMap({ $0 }).joined(separator: "\n")
        let activityViewController = UIActivityViewController(activityItems: [textToShare], applicationActivities: nil)
        let topViewController = Utils.getTopController()
        activityViewController.popoverPresentationController?.sourceView = topViewController?.view
        topViewController?.present(activityViewController, animated: true, completion: nil)
    }
}
