//
//  ArticleWebViewInteractor.swift
//  PocketReader
//
//  Created by Jakub Lares on 20.08.18.
//  Copyright (c) 2018 Jakub Lares. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleWebViewBusinessLogic {
    func getArticleUrl()
    func shareArticle()
}

protocol ArticleWebViewDataStore {
    var article: ArticlesFeed.GetArticles.Article? { get set }
}

class ArticleWebViewInteractor: ArticleWebViewBusinessLogic, ArticleWebViewDataStore {

    var presenter: ArticleWebViewPresentationLogic?
    var article: ArticlesFeed.GetArticles.Article?
    private let shareWorker = ShareWorker()

    func getArticleUrl() {
        presenter?.presentArticleUrl(article?.url)
    }

    func shareArticle() {
        shareWorker.shareArticle(article)
    }
}
