//
//  ArticleWebViewRouter.swift
//  PocketReader
//
//  Created by Jakub Lares on 20.08.18.
//  Copyright (c) 2018 Jakub Lares. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ArticleWebViewRoutingLogic {
}

protocol ArticleWebViewDataPassing {
    var dataStore: ArticleWebViewDataStore? { get }
}

class ArticleWebViewRouter: NSObject, ArticleWebViewRoutingLogic, ArticleWebViewDataPassing {
    
    weak var viewController: ArticleWebViewViewController?
    var dataStore: ArticleWebViewDataStore?
}
