//
//  ArticlesFeedModels.swift
//  PocketReader
//
//  Created by Jakub Lares on 18.08.18.
//  Copyright (c) 2018 Jakub Lares. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ArticlesFeed {

    enum GetArticles {

        struct Response: Decodable {
            let status, source, sortBy: String?
            let articles: [Article]?
        }

        struct Article: Decodable {
            let author, title, description, url: String?
            let urlToImage: String?
            let publishedAt: Date?
        }
        
        struct ViewModel {
            let articles: [ArticleViewModel]
        }

        struct ArticleViewModel {
            let title: String
            let published: String
            let imageUrl: URL?
        }
    }

    enum GetArticleDetail {

        struct ViewModel {
            let title: String
            let published: String
            let imageUrl: URL?
            let author: String
            let description: String
        }
    }
}
